version: '3.8'

services:
  home-server:
    build:
      context: .
      dockerfile: cmd/home-server/Dockerfile
    ports:
      - "5005:5005"
    container_name: home-server
    environment:
      - STAGE=local

  pi-agent:
    build:
      context: .
      dockerfile: cmd/pi-agent/Dockerfile
    ports:
      - "50051:50051"
    container_name: pi-agent
    environment:
      - STAGE=local

  pi-agent-controller:
    build:
      context: .
      dockerfile: cmd/pi-agent-controller/Dockerfile
    ports:
      - "50052:50052"
    container_name: pi-agent-controller
    depends_on:
      - pi-agent
    environment:
      - STAGE=local