version: '3.8'

services:
  pi-controller-processor:
    build:
      context: .
      dockerfile: cmd/pi-controller-processor/Dockerfile
    ports:
      - "5005:5005"
    container_name: pi-controller-processor
    environment:
      - STAGE=local

  pi-controller:
    build:
      context: .
      dockerfile: cmd/pi-controller/Dockerfile
    ports:
      - "50051:50051"
    container_name: pi-controller
    environment:
      - STAGE=local

  pi-gateway:
    build:
      context: .
      dockerfile: cmd/pi-gateway/Dockerfile
    ports:
      - "50052:50052"
    container_name: pi-gateway
    depends_on:
      - pi-controller
    environment:
      - STAGE=local