// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/types/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Operation request and response objects
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Parameters    *StreamParameter       `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_types_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_types_api_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamRequest) GetParameters() *StreamParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type StreamParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamParameter) Reset() {
	*x = StreamParameter{}
	mi := &file_api_types_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamParameter) ProtoMessage() {}

func (x *StreamParameter) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamParameter.ProtoReflect.Descriptor instead.
func (*StreamParameter) Descriptor() ([]byte, []int) {
	return file_api_types_api_proto_rawDescGZIP(), []int{1}
}

func (x *StreamParameter) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_api_types_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_api_types_api_proto_rawDescGZIP(), []int{2}
}

func (x *OperationResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OperationResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OperationResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_api_types_api_proto protoreflect.FileDescriptor

const file_api_types_api_proto_rawDesc = "" +
	"\n" +
	"\x13api/types/api.proto\x12\x10homeserver.proto\x1a\x1bgoogle/protobuf/empty.proto\"o\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12A\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2!.homeserver.proto.StreamParameterR\n" +
	"parameters\")\n" +
	"\x0fStreamParameter\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"m\n" +
	"\x11OperationResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output2\xbf\x01\n" +
	"\x11PiAgentController\x12Y\n" +
	"\x0fconfigureStream\x12\x1f.homeserver.proto.StreamRequest\x1a#.homeserver.proto.OperationResponse\"\x00\x12O\n" +
	"\x0eretrieveStatus\x12\x16.google.protobuf.Empty\x1a#.homeserver.proto.OperationResponse\"\x00B-Z+github.com/vincentvtran/pi-controller/protob\x06proto3"

var (
	file_api_types_api_proto_rawDescOnce sync.Once
	file_api_types_api_proto_rawDescData []byte
)

func file_api_types_api_proto_rawDescGZIP() []byte {
	file_api_types_api_proto_rawDescOnce.Do(func() {
		file_api_types_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_types_api_proto_rawDesc), len(file_api_types_api_proto_rawDesc)))
	})
	return file_api_types_api_proto_rawDescData
}

var file_api_types_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_types_api_proto_goTypes = []any{
	(*StreamRequest)(nil),     // 0: homeserver.proto.StreamRequest
	(*StreamParameter)(nil),   // 1: homeserver.proto.StreamParameter
	(*OperationResponse)(nil), // 2: homeserver.proto.OperationResponse
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_api_types_api_proto_depIdxs = []int32{
	1, // 0: homeserver.proto.StreamRequest.parameters:type_name -> homeserver.proto.StreamParameter
	0, // 1: homeserver.proto.PiAgentController.configureStream:input_type -> homeserver.proto.StreamRequest
	3, // 2: homeserver.proto.PiAgentController.retrieveStatus:input_type -> google.protobuf.Empty
	2, // 3: homeserver.proto.PiAgentController.configureStream:output_type -> homeserver.proto.OperationResponse
	2, // 4: homeserver.proto.PiAgentController.retrieveStatus:output_type -> homeserver.proto.OperationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_types_api_proto_init() }
func file_api_types_api_proto_init() {
	if File_api_types_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_types_api_proto_rawDesc), len(file_api_types_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_types_api_proto_goTypes,
		DependencyIndexes: file_api_types_api_proto_depIdxs,
		MessageInfos:      file_api_types_api_proto_msgTypes,
	}.Build()
	File_api_types_api_proto = out.File
	file_api_types_api_proto_goTypes = nil
	file_api_types_api_proto_depIdxs = nil
}
