// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: src/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Operation request and response objects
type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Param         *OperationParameter    `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_src_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OperationRequest) GetParam() *OperationParameter {
	if x != nil {
		return x.Param
	}
	return nil
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_src_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OperationResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// *
// Operation input parameter object
type OperationParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationParameter) Reset() {
	*x = OperationParameter{}
	mi := &file_src_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationParameter) ProtoMessage() {}

func (x *OperationParameter) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationParameter.ProtoReflect.Descriptor instead.
func (*OperationParameter) Descriptor() ([]byte, []int) {
	return file_src_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *OperationParameter) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_src_proto_api_proto protoreflect.FileDescriptor

const file_src_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x13src/proto/api.proto\x12\x10homeserver.proto\"g\n" +
	"\x10OperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\x05param\x18\x02 \x01(\v2$.homeserver.proto.OperationParameterR\x05param\"L\n" +
	"\x11OperationResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\".\n" +
	"\x12OperationParameter\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload2b\n" +
	"\vHomeService\x12S\n" +
	"\x06invoke\x12\".homeserver.proto.OperationRequest\x1a#.homeserver.proto.OperationResponse\"\x00B*Z(github.com/vincentvtran/homeserver/protob\x06proto3"

var (
	file_src_proto_api_proto_rawDescOnce sync.Once
	file_src_proto_api_proto_rawDescData []byte
)

func file_src_proto_api_proto_rawDescGZIP() []byte {
	file_src_proto_api_proto_rawDescOnce.Do(func() {
		file_src_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_api_proto_rawDesc), len(file_src_proto_api_proto_rawDesc)))
	})
	return file_src_proto_api_proto_rawDescData
}

var file_src_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_proto_api_proto_goTypes = []any{
	(*OperationRequest)(nil),   // 0: homeserver.proto.OperationRequest
	(*OperationResponse)(nil),  // 1: homeserver.proto.OperationResponse
	(*OperationParameter)(nil), // 2: homeserver.proto.OperationParameter
}
var file_src_proto_api_proto_depIdxs = []int32{
	2, // 0: homeserver.proto.OperationRequest.param:type_name -> homeserver.proto.OperationParameter
	0, // 1: homeserver.proto.HomeService.invoke:input_type -> homeserver.proto.OperationRequest
	1, // 2: homeserver.proto.HomeService.invoke:output_type -> homeserver.proto.OperationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_api_proto_init() }
func file_src_proto_api_proto_init() {
	if File_src_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_api_proto_rawDesc), len(file_src_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_api_proto_goTypes,
		DependencyIndexes: file_src_proto_api_proto_depIdxs,
		MessageInfos:      file_src_proto_api_proto_msgTypes,
	}.Build()
	File_src_proto_api_proto = out.File
	file_src_proto_api_proto_goTypes = nil
	file_src_proto_api_proto_depIdxs = nil
}
